name = "pengeluaran"
#type = "javascript"  # atau "module" jika kamu menulis dalam format ESM
main = "dist/index.js"
compatibility_date = "2025-06-22"

[build]
# command = "npm run build"

[vars]
# Jika kamu punya environment variables, bisa tambahkan di sini
TELEGRAM_TOKEN = "7823679916:AAGPLub5GJ0UprX5Zd_eQqytfiqDurlBqmw"
# GOOGLE_SHEET_ID = "https://script.google.com/macros/s/AKfycbx6e3qdBUpyV-rZnDaWtXvykbiacqeNaeO56xB3SymnfK5ErwMxEw2aIRsS2_8UQOUo/exec"
WEB_APP_URL = "https://script.google.com/macros/s/AKfycbx6e3qdBUpyV-rZnDaWtXvykbiacqeNaeO56xB3SymnfK5ErwMxEw2aIRsS2_8UQOUo/exec"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "TELEGRAM_STATE"
id = "2e543f2a769a4187bcc1d81d7dc05441"
