name = "pengeluaran"
#type = "javascript"  # atau "module" jika kamu menulis dalam format ESM
main = "dist/index.js"
compatibility_date = "2025-06-22"

[build]
# command = "npm run build"

[vars]
# Jika kamu punya environment variables, bisa tambahkan di sini
TELEGRAM_TOKEN = "7823679916:AAGPLub5GJ0UprX5Zd_eQqytfiqDurlBqmw"
# GOOGLE_SHEET_ID = "your-sheet-id"
